<!doctype html>
<!--[if (IE 8)&!(IEMobile)]>
<html class="no-js is-ie8 lt-ie9 lt-ie10" lang="en">
<![endif]-->
<!--[if IE 9]>
    <html class="no-js is-ie9 lt-ie10" lang="en">
<![endif]-->
<!--[if gt IE 9]><!-->
<html lang="en">
<!--<![endif]-->
<head>
<title>{% block pageTitle %}{% endblock %} {{ global.pageTitleFragment }}</title>
</head>
<body>

{% block content %}
{% endblock %}

</body>
</html>